version: '3.8'
services:
  app:
    build: .
    volumes:
      - ./django
    ports:
      - '8000:8000'
    container_name: web-photo
    command: bash -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    depends_on:
      - db
    networks:
      - photo_network

  db:
    image: mysql
    container_name: photo-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: photo
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - '3307:3306'
    volumes:
      - ./db:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - photo_network
networks:
  photo_network: